version: "2"
services:
  build-root:
    build: .
    volumes:
      - ./:/root/game/
    working_dir: /root/game/
    environment:
      - BUILD_ENV=${BUILD_ENV}

  dev:
    extends:
      service: build-root
    command: bash

  build-mac:
    extends:
      service: build-root
    command: sh -c "mkdir -v -p dist/mac && godot -v --export 'Mac OSX' dist/mac/game.zip"

  build-windows:
    extends:
      service: build-root
    command: sh -c "mkdir -v -p dist/windows && godot -v --export 'Windows Desktop' dist/windows/game.exe"

  build-web:
    extends:
      service: build-root
    command: sh -c "mkdir -v -p dist/web && godot -v --export 'HTML5' dist/web/index.html"

  build-x11:
    extends:
      service: build-root
    command: sh -c "mkdir -v -p dist/x11 && godot -v --export 'Linux/X11' dist/x11/game.x86_64"
